### ISSUE TITLE
chapter6.md的图不完整

### ISSUE THREAD

**Issue by ghost** [JerryC8080/understand-tcp-udp#2]

**Comment by JerryC8080** [comment]
@wj5346599  
Socket 各个函数是对 TCP 通信的封装，如果要讲得足够详细，可以说到具体每个 TCP 报文的内容结构。
抽象和具体是相对的，而人的思维更擅长接受概括性的概念，我认为在一张图中描绘太多的细节，反而会适得其反。
如果你读完之后，觉得意犹未尽，想探索更加详细的 TCP 内容，可以参考《计算机网络》一书。
